spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/eq
    username: eq
    password: eq

  flyway:
    enabled: true

  jpa:
    hibernate:
      ddl-auto: validate
  open-in-view: false

